type StyleCategoryType = {
  name: string;
  subStyles: string[];
};

export const stylesData: StyleCategoryType[] = [
  {
    name: "Casual",
    subStyles: [
      "Urban",
      "Normcore",
      "Athleisure",
      "Minimalist",
      "Smart",
      "Loungewear",
      "Comfycore",
    ],
  },
  {
    name: " Classic",
    subStyles: [
      "Preppy",
      "Business",
      "Elegant",
      "Parisian",
      "Traditional",
      "Tailored",
      "Ivy",
      "Corporate",
    ],
  },
  {
    name: "Glam",
    subStyles: [
      "Eveningwear",
      "Club Glam",
      "Maximalist",
      "Red Carpet",
      "Sexy Chic",
      "Luxe",
      "Cocktail",
      "Opulent",
    ],
  },
  {
    name: "Vintage",
    subStyles: [
      "1920s",
      "1940s",
      "1950s",
      "Rockabilly",
      "1960s",
      "Mod",
      "1970s",
      "Bohemian",
      "1980s",
      "Retro",
      "1990s",
      "Y2K",
      "Old Hollywood",
    ],
  },
  {
    name: "Alternative",
    subStyles: [
      "Gothic",
      "Punk",
      "Emo",
      "Metal",
      "Indie",
      "Grunge",
      "Rocker",
      "Cyberpunk",
      "Skater",
      "Anarcho",
    ],
  },
  {
    name: "Cultural",
    subStyles: [
      "Afro",
      "East Asian",
      "South Asian",
      "Middle Eastern",
      "Indigenous",
      "Latin",
      "Scandinavian",
      "Mediterranean",
    ],
  },
  {
    name: "Conceptual",
    subStyles: [
      "Avant-Garde",
      "Deconstructed",
      "Futuristic",
      "Androgynous",
      "Experimental",
      "Tech",
      "Sculptural",
    ],
  },
  {
    name: "Functional",
    subStyles: [
      "Workwear",
      "Techwear",
      "Military",
      "Outdoor",
      "Hiking",
      "Gorpcore",
      "Survivalwear",
    ],
  },
  {
    name: "Thematic",
    subStyles: [
      "Western",
      "Cowboy/girl",
      "Biker",
      "Racer",
      "Dark Academia",
      "Light Academia",
      "Fantasy",
      "Sci-Fi",
      "Fairycore",
      "Cottagecore",
      "Royalcore",
    ],
  },
  {
    name: "Subcultural",
    subStyles: [
      "Art School",
      "Kawaii",
      "Lolita",
      "Harajuku",
      "K-Fashion",
      "J-Fashion",
      "Baddie",
      "Soft Girl",
      "E-Girl/Boy",
      "Vaporwave",
      "Twee",
      "Mall Goth",
      "Kidcore",
    ],
  },
];
