import { JSX } from "react";
import type { Metadata } from "next";
import { Header } from "@/app/@ui";
import { UserProvider } from "./@contexts/UserContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  contexts: React.ReactNode;
  svgs: React.ReactNode;
  ui: React.ReactNode;
  utils: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Header />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
