import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "@/app/ui";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const exatCyr = localFont({
  src: [
    {
      path: "../public/fonts/exatcyr/exatcyr-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/exatcyr/exatcyr-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/exatcyr/exatcyr-bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={exatCyr.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
